site_name: Notas Musicais
repo_url: https://github.com/gabrielustosa/notas-musicais
repo_name: gabrielustosa/notas-musicais
edit_uri: tree/master

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [ notas_musicais ]