site_name: Notas Musicais
repo_url: https://github.com/gabrielustosa/notas-musicais
repo_name: gabrielustosa/notas-musicais
edit_uri: tree/master

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

watch:
  - notas_musicais

plugins:
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [ notas_musicais ]

extra:
  commands:
    run: poetry run notas-musicais
